default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: fan_site_development

test:
  <<: *default
  database: fan_site_test

production:
  <<: *default
  database: fan_site_production
  username: fan_site
  password: <%= ENV['FAN_SITE_DATABASE_PASSWORD'] %>
